// Interface automatically generated by schemas-to-ts

import { Post } from '../../api/post';
import { Post_Plain } from '../../api/post';

export interface Latest_3 {
  posts: { data: Post[] };
}
export interface Latest_3_Plain {
  posts: Post_Plain[];
}

export interface Latest_3_NoRelations {
  posts: number[];
}

