// Interface automatically generated by schemas-to-ts

import { Tag } from './Tag';
import { Tag_Plain } from './Tag';
import { Tag_NoRelations } from './Tag';

export interface Filter {
  name: string;
  data?: any;
  tags: Tag[];
}
export interface Filter_Plain {
  name: string;
  data?: any;
  tags: Tag_Plain[];
}

export interface Filter_NoRelations {
  name: string;
  data?: any;
  tags: Tag_NoRelations[];
}

