// Interface automatically generated by schemas-to-ts

export interface Tag {
  value?: string;
}
export interface Tag_Plain {
  value?: string;
}

export interface Tag_NoRelations {
  value?: string;
}

