// Interface automatically generated by schemas-to-ts

export interface Bird {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    speciesCode?: string;
    comName: string;
    sciName?: string;
    category?: string;
    taxonOrder?: number;
    order?: string;
    familyCode?: string;
    familyComName?: string;
    FamilySciName?: string;
  };
}
export interface Bird_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  speciesCode?: string;
  comName: string;
  sciName?: string;
  category?: string;
  taxonOrder?: number;
  order?: string;
  familyCode?: string;
  familyComName?: string;
  FamilySciName?: string;
}

export interface Bird_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  speciesCode?: string;
  comName: string;
  sciName?: string;
  category?: string;
  taxonOrder?: number;
  order?: string;
  familyCode?: string;
  familyComName?: string;
  FamilySciName?: string;
}

export interface Bird_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  speciesCode?: string;
  comName: string;
  sciName?: string;
  category?: string;
  taxonOrder?: number;
  order?: string;
  familyCode?: string;
  familyComName?: string;
  FamilySciName?: string;
}
