// Interface automatically generated by schemas-to-ts

export interface Bird {
  documentId: string;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;
  speciesCode?: string;
  comName: string;
  sciName?: string;
  category?: string;
  taxonOrder?: number;
  order?: string;
  familyCode?: string;
  familyComName?: string;
  FamilySciName?: string;
}
export interface Bird_Plain {
  documentId: string;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;
  speciesCode?: string;
  comName: string;
  sciName?: string;
  category?: string;
  taxonOrder?: number;
  order?: string;
  familyCode?: string;
  familyComName?: string;
  FamilySciName?: string;
}

export interface Bird_NoRelations {
  documentId: string;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;
  speciesCode?: string;
  comName: string;
  sciName?: string;
  category?: string;
  taxonOrder?: number;
  order?: string;
  familyCode?: string;
  familyComName?: string;
  FamilySciName?: string;
}

export interface Bird_AdminPanelLifeCycle {
  documentId: string;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;
  speciesCode?: string;
  comName: string;
  sciName?: string;
  category?: string;
  taxonOrder?: number;
  order?: string;
  familyCode?: string;
  familyComName?: string;
  FamilySciName?: string;
}
