// Interface automatically generated by schemas-to-ts

import { Photo } from './photo';
import { Filter } from '../components/gallery/Filter';
import { Photo_Plain } from './photo';
import { Filter_Plain } from '../components/gallery/Filter';
import { Filter_NoRelations } from '../components/gallery/Filter';
import { AdminPanelRelationPropertyModification } from '../common/AdminPanelRelationPropertyModification';

export interface GalleryView {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title?: string;
    photos: { data: Photo[] };
    filters: Filter[];
  };
}
export interface GalleryView_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  photos: Photo_Plain[];
  filters: Filter_Plain[];
}

export interface GalleryView_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  photos: number[];
  filters: Filter_NoRelations[];
}

export interface GalleryView_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  photos: AdminPanelRelationPropertyModification<Photo_Plain>;
  filters: Filter_Plain[];
}
