// Interface automatically generated by schemas-to-ts

import { Photo } from './photo';
import { Photo_Plain } from './photo';
import { AdminPanelRelationPropertyModification } from '../common/AdminPanelRelationPropertyModification';

export interface Gallery {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    photos: { data: Photo[] };
  };
}
export interface Gallery_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  photos: Photo_Plain[];
}

export interface Gallery_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  photos: number[];
}

export interface Gallery_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  photos: AdminPanelRelationPropertyModification<Photo_Plain>;
}
