// Interface automatically generated by schemas-to-ts

import { Photo } from './photo';
import { Filter } from '../components/gallery/Filter';
import { Photo_Plain } from './photo';
import { Filter_Plain } from '../components/gallery/Filter';
import { Filter_NoRelations } from '../components/gallery/Filter';
import { AdminPanelRelationPropertyModification } from '../common/AdminPanelRelationPropertyModification';

export interface GalleryView {
  documentId: string;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;
  title?: string;
  photos: { data: Photo[] };
  filters: Filter[];
  quick_search?: boolean;
}
export interface GalleryView_Plain {
  documentId: string;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;
  title?: string;
  photos: Photo_Plain[];
  filters: Filter_Plain[];
  quick_search?: boolean;
}

export interface GalleryView_NoRelations {
  documentId: string;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;
  title?: string;
  photos: number[];
  filters: Filter_NoRelations[];
  quick_search?: boolean;
}

export interface GalleryView_AdminPanelLifeCycle {
  documentId: string;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;
  title?: string;
  photos: AdminPanelRelationPropertyModification<Photo_Plain>;
  filters: Filter_Plain[];
  quick_search?: boolean;
}
