// Interface automatically generated by schemas-to-ts

import { Media } from '../common/Media';
import { Collection } from './collection';
import { Bird } from './bird';
import { Media_Plain } from '../common/Media';
import { Collection_Plain } from './collection';
import { Bird_Plain } from './bird';
import { AdminPanelRelationPropertyModification } from '../common/AdminPanelRelationPropertyModification';

export interface Photo {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    photo: { data: Media };
    title?: string;
    color?: any;
    collections?: { data: Collection[] };
    EXIF?: any;
    internal_id?: string;
    iso?: number;
    aperture?: number;
    focal_length?: number;
    camera_body?: string;
    camera_lens?: string;
    mode?: string;
    last_modified?: Date;
    taken?: Date;
    metering_mode?: string;
    shutter_speed?: number;
    birds: { data: Bird[] };
  };
}
export interface Photo_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  photo: Media_Plain;
  title?: string;
  color?: any;
  collections?: Collection_Plain[];
  EXIF?: any;
  internal_id?: string;
  iso?: number;
  aperture?: number;
  focal_length?: number;
  camera_body?: string;
  camera_lens?: string;
  mode?: string;
  last_modified?: Date;
  taken?: Date;
  metering_mode?: string;
  shutter_speed?: number;
  birds: Bird_Plain[];
}

export interface Photo_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  photo: number;
  title?: string;
  color?: any;
  collections?: number[];
  EXIF?: any;
  internal_id?: string;
  iso?: number;
  aperture?: number;
  focal_length?: number;
  camera_body?: string;
  camera_lens?: string;
  mode?: string;
  last_modified?: Date;
  taken?: Date;
  metering_mode?: string;
  shutter_speed?: number;
  birds: number[];
}

export interface Photo_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  photo: AdminPanelRelationPropertyModification<Media_Plain>;
  title?: string;
  color?: any;
  collections?: AdminPanelRelationPropertyModification<Collection_Plain>;
  EXIF?: any;
  internal_id?: string;
  iso?: number;
  aperture?: number;
  focal_length?: number;
  camera_body?: string;
  camera_lens?: string;
  mode?: string;
  last_modified?: Date;
  taken?: Date;
  metering_mode?: string;
  shutter_speed?: number;
  birds: AdminPanelRelationPropertyModification<Bird_Plain>;
}
