// Interface automatically generated by schemas-to-ts

import { Media } from '../common/Media';
import { Bird } from './bird';
import { Media_Plain } from '../common/Media';
import { Bird_Plain } from './bird';
import { AdminPanelRelationPropertyModification } from '../common/AdminPanelRelationPropertyModification';

export interface Temp {
  documentId: string;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;
  title?: string;
  photo?: { data: Media };
  exif?: any;
  iso?: number;
  taken?: Date;
  zone?: any;
  key?: any;
  filters?: any;
  birds: { data: Bird[] };
}
export interface Temp_Plain {
  documentId: string;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;
  title?: string;
  photo?: Media_Plain;
  exif?: any;
  iso?: number;
  taken?: Date;
  zone?: any;
  key?: any;
  filters?: any;
  birds: Bird_Plain[];
}

export interface Temp_NoRelations {
  documentId: string;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;
  title?: string;
  photo?: number;
  exif?: any;
  iso?: number;
  taken?: Date;
  zone?: any;
  key?: any;
  filters?: any;
  birds: number[];
}

export interface Temp_AdminPanelLifeCycle {
  documentId: string;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;
  title?: string;
  photo?: AdminPanelRelationPropertyModification<Media_Plain>;
  exif?: any;
  iso?: number;
  taken?: Date;
  zone?: any;
  key?: any;
  filters?: any;
  birds: AdminPanelRelationPropertyModification<Bird_Plain>;
}
