// Interface automatically generated by schemas-to-ts

import { Media } from '../common/Media';
import { Media_Plain } from '../common/Media';
import { AdminPanelRelationPropertyModification } from '../common/AdminPanelRelationPropertyModification';

export interface Temp {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title?: string;
    photo?: { data: Media };
    exif?: any;
    iso?: number;
    taken?: Date;
  };
}
export interface Temp_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  photo?: Media_Plain;
  exif?: any;
  iso?: number;
  taken?: Date;
}

export interface Temp_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  photo?: number;
  exif?: any;
  iso?: number;
  taken?: Date;
}

export interface Temp_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  photo?: AdminPanelRelationPropertyModification<Media_Plain>;
  exif?: any;
  iso?: number;
  taken?: Date;
}
